### ISSUE TITLE
apply over an index

### ISSUE THREAD

**Issue by cmacdonald** [terrierteam/pyterrier_dr#14]
In the FCRS usecase (w/ @yashonwu), we have a need to take a (dense) index, and apply a "model" to it, to make a new index. I think it would make sense to replace our custom index and ranking code with pyterrier_dr.

Currently, that just means applying an torch.nn.Linear. This can be done using a GPU, batchwise. More generically, it could be a function. What could be a reasonable API for PyTerrier DR?

```python
index_new = index.downcast( model.img_transform, batchsize=K, device=torch.cuda() ) 
```

I wouldnt expect all indices to support this. I think some FAISS impls could support it, but all I really care about is the numpy index impl.

**Comment by seanmacavaney** [comment]
So the `FlexIndex` under the refactor branch exposes a `get_corpus_iter()` method, which yields `{'docno': ..., 'doc_vec': ...}` records.

Using this, `model` could behave just as any other transformer would, by operating as a `D->D` transformer (replacing the `doc_vec` of each record). This design would allow `model` to also compose directly over a document encoder model.

Example:

```python
index = FlexIndex(...)
model = FCRS(...)
new_index = FlexIndex(...)
pipeline = model >> new_index
pipeline.index(index.get_corpus_iter())

# which would have the same effect as
orig_model = MyDenseModel(...) # whatever model was used to crease index above
model = FCRS(...)
new_index = FlexIndex(...)
pipeline = orig_model >> model >> new_index
pipeline.index(dataset.get_corpus_iter())
```

Do you think this would meet your needs?

**Comment by seanmacavaney** [comment]
(If you already have `NumpyIndex`es built, they can pretty easily be converted to `FlexIndex`es.)

**Comment by seanmacavaney** [comment]
Does this meet your needs?

**Comment by cmacdonald** [comment]
Probably, thanks!
