### ISSUE TITLE
Error code 139

### ISSUE THREAD

**Issue by oussaidene** [terrierteam/pyterrier_dr#9]
Hi,

While trying to index the Arguana collection and then run an experiment on it i encounter the error code 139. From what i understand it's a segmentation violation error, but i don't understand where it is comming from.

Here's my code:
`
dataset = pt.get_dataset('irds:beir/arguana')
index = pyterrier_dr.NumpyIndex('index_arg.np')
idx_pipeline = model >> index
idx_pipeline.index(dataset.get_corpus_iter())

retr_pipeline = model >> index
pt.Experiment(
    [retr_pipeline],
    dataset.get_topics(),
    dataset.get_qrels(),
    eval_metrics=["map", "recip_rank",RR@10,"ndcg", "ndcg_cut_10"]
)
`

and i get this :
`
beir/arguana documents: 100%|██████████| 8674/8674 [15:44<00:00,  9.19it/s]srun: error: gpu-nc07: task 0: Exited with exit code 139
`

If anyone knows anything about this please let me know.
Thank you.

**Comment by seanmacavaney** [comment]
Interesting -- that pipeline isn't doing anything that I'd expect to give a segmentation fault -- it's just using numpy/torch, which tend to be very robust to those types of errors.

When I tried the above pipeline (using `TctColBert`), it finished without error.

Can you provide a few details on your platform/versions/etc? E.g., what python version, OS, numpy, and torch version are you using?

**Comment by oussaidene** [comment]
I'm using 
OS: centOS Linux (version 7)
python: 3.8
torch: 1.9.0a0+df837d0
numpy: 1.19.2

**Comment by oussaidene** [comment]
Update: the problem is solved by upgrading numpy to 1.24

**Comment by seanmacavaney** [comment]
Interesting, thanks!
